corpus/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/', views.DetailView.as_view(), name='detail')
]

visualizer/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^$', include('corpus.urls')),
    url(r'^corpus/', include('corpus.urls')),
    url(r'^admin/', admin.site.urls),
]

corpus/models.py
from django.db import models


class ParallelCorpus(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class ParallelSentence(models.Model):
    src = models.TextField()
    tgt = models.TextField()
    parallel_corpus = models.ForeignKey(ParallelCorpus, on_delete=models.CASCADE)

    def __str__(self):
        return self.src + " ⇔  " + self.tgt

class AlignmentModel(models.Model):
    log = models.TextField()


class Alignment(models.Model):
    alignment = models.TextField()
    parallel_sentence = models.ForeignKey(ParallelCorpus, on_delete=models.CASCADE)
    alignment_model = models.ForeignKey(AlignmentModel, on_delete=models.CASCADE)

corpus/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import ParallelCorpus


class IndexView(generic.ListView):
    template_name = "corpus/index.html"
    context_object_name = "corpora"

    def get_queryset(self):
        return ParallelCorpus.objects.all()


class DetailView(generic.DetailView):
    model = ParallelCorpus
    template_name = "corpus/corpus_index.html"

corpus/templates/corpus/corpus_index.html
<table>
<tr>
    <th>原言語</th>
    <th>目的言語</th>
</tr>
{% for para in parallelcorpus.parallelsentence_set.all %}
        <tr>
        <td>{{ para.src }}</td>
        <td>{{ para.tgt }}</td>
        </tr>
{% endfor %}
</table>

corpus/templates/corpus/index.html
{% if corpora %}
    <ul>
    {% for corpus in corpora %}
        <li><a href="/corpus/{{ corpus.id }}/">{{ corpus.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No corpora are available.</p>
{% endif %}